sudo: required
services:
  - docker

before_install:
  - docker build -t gambe94/dockerReact -f Dockerfile.dev .


script:
  - docker run -e CI=true gambe94/dockerReact npm run test

language: generic 
